Repository LLNL/variorum, pull requests merged in 2022-05, with the labels that each got.

#194 Extend JSON API and Best Effort Node Power Cap to other architectures
  src/variorum/ARM/ARM.c
  src/variorum/ARM/ARM.h
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/power_features.c
  src/variorum/ARM/power_features.h
  src/variorum/IBM/ibm_sensors.c
  src/variorum/Intel/Haswell_3F.c
  src/variorum/Intel/Haswell_3F.h
  src/variorum/Intel/IvyBridge_3E.c
  src/variorum/Intel/IvyBridge_3E.h
  src/variorum/Intel/KabyLake_9E.c
  src/variorum/Intel/KabyLake_9E.h
  src/variorum/Intel/SandyBridge_2A.c
  src/variorum/Intel/SandyBridge_2A.h
  src/variorum/Intel/SandyBridge_2D.c
  src/variorum/Intel/SandyBridge_2D.h
  src/variorum/Intel/Skylake_55.c
  src/variorum/Intel/Skylake_55.h
  src/variorum/Intel/config_intel.c
  src/variorum/Intel/power_features.c
Labels: enhancement, Ready-For-Review

#196 AMD Variorum port (with contributions from AMD team)
  host-configs/epyc-x86_64-gcc@8.4.0.cmake
  host-configs/pluto5-rhel_x86_64-gcc@8.4.1.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMake/thirdparty/Setupesmi.cmake
  src/docs/sphinx/AMD.rst
  src/examples/CMakeLists.txt
  src/examples/variorum-print-energy-example.c
  src/variorum/AMD/CMakeLists.txt
  src/variorum/AMD/config_amd.c
  src/variorum/AMD/config_amd.h
  src/variorum/AMD/energy_feature.c
  src/variorum/AMD/energy_feature.h
  src/variorum/AMD/epyc.c
  src/variorum/AMD/epyc.h
  src/variorum/AMD/msr_core.c
  src/variorum/AMD/msr_core.h
  src/variorum/CMakeLists.txt
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.c
  src/variorum/variorum.h
Labels: enhancement, Ready-For-Review

#227 Documentation Edits.
  README
  src/docs/sphinx/AMD.rst
  src/docs/sphinx/HWArchitectures.rst
  src/docs/sphinx/Intel.rst
  src/docs/sphinx/VariorumAPI.rst
  src/docs/sphinx/VariorumDevel.rst
  src/docs/sphinx/VariorumTools.rst
Labels: Ready-For-Review

#219 add gcc version to build matrix
  .github/workflows/github-actions.yml
Labels: Ready-For-Review

#240 Refactor msr core
  src/variorum/AMD/CMakeLists.txt
  src/variorum/CMakeLists.txt
  src/variorum/Intel/CMakeLists.txt
  src/variorum/Intel/msr_core.c
  src/variorum/Intel/msr_core.h
  src/variorum/msr/CMakeLists.txt
  src/variorum/msr/msr_core.c
  src/variorum/msr/msr_core.h
Labels: enhancement
