Repository LLNL/variorum, pull requests merged in 2022-09, with the labels that each got.

#323 fortran wrapper update
  src/examples/CMakeLists.txt
  src/examples/fortran-examples/CMakeLists.txt
  src/examples/fortran-examples/variorum-print-power-fortran-example.f90
  src/examples/fortran-examples/variorum-print-thermals-fortran-example.f90
  src/variorum/CMakeLists.txt
  src/wrappers/fortran/variorum.f90
Labels: type-internal-cleanup, status-revisions-needed, area-internal

#333 Append _GPU to Nvidia folder name for clarity, update CMakeLists.
  src/variorum/CMakeLists.txt
  src/variorum/Nvidia_GPU/CMakeLists.txt
  src/variorum/Nvidia_GPU/Volta.c
  src/variorum/Nvidia_GPU/Volta.h
  src/variorum/Nvidia_GPU/config_nvidia.c
  src/variorum/Nvidia_GPU/config_nvidia.h
  src/variorum/Nvidia_GPU/power_features.c
  src/variorum/Nvidia_GPU/power_features.h
Labels: status-ready-for-review, type-internal-cleanup, area-build-system, area-internal

#314 Apmidg monitor patch
  README
  host-configs/arcticus-apmidg-oneapi.cmake
  src/CMake/CMakeBasics.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMake/thirdparty/FindAPMIDG.cmake
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/docs/sphinx/HWArchitectures.rst
  src/docs/sphinx/IntelGPU.rst
  src/examples/CMakeLists.txt
  src/examples/openmp-examples/CMakeLists.txt
  src/powmon/CMakeLists.txt
  src/tests/variorum/CMakeLists.txt
  src/variorum/CMakeLists.txt
  src/variorum/Intel_GPU/CMakeLists.txt
  src/variorum/Intel_GPU/GPU.c
  src/variorum/Intel_GPU/GPU.h
  src/variorum/Intel_GPU/config_intel_gpu.c
  src/variorum/Intel_GPU/config_intel_gpu.h
  src/variorum/Intel_GPU/power_features.c
  src/variorum/Intel_GPU/power_features.h
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.h
  src/variorum/variorum_config.h.in
  src/variorum/variorum_error.c
Labels: status-ready-for-review, type-feature, area-hardware-support

#293 Python API initial support, based on new JSON API with char**
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/examples/CMakeLists.txt
  src/examples/python-examples/CMakeLists.txt
  src/examples/python-examples/variorum-cap-best-effort-node-power-limit-python-example.py
  src/examples/python-examples/variorum-cap-gpu-power-ratio-python-example.py
  src/examples/python-examples/variorum-cap-socket-power-limit-python-example.py
  src/examples/python-examples/variorum-get-current-version-python-example.py
  src/examples/python-examples/variorum-get-node-power-domain-info-json-python-example.py
  src/examples/python-examples/variorum-get-node-power-json-python-example.py
  src/examples/python-examples/variorum-print-available-frequencies-python-example.py
  src/examples/python-examples/variorum-print-counters-python-example.py
  src/examples/python-examples/variorum-print-features-python-example.py
  src/examples/python-examples/variorum-print-frequency-python-example.py
  src/examples/python-examples/variorum-print-gpu-utilization-python-example.py
  src/examples/python-examples/variorum-print-hyperthreading-python-example.py
  src/examples/python-examples/variorum-print-power-limit-python-example.py
  src/examples/python-examples/variorum-print-power-python-example.py
  src/examples/python-examples/variorum-print-thermals-python-example.py
  src/examples/python-examples/variorum-print-topology-python-example.py
  src/examples/python-examples/variorum-print-turbo-python-example.py
  src/examples/python-examples/variorum-print-verbose-counters-python-example.py
  src/examples/python-examples/variorum-print-verbose-frequency-python-example.py
  src/examples/python-examples/variorum-print-verbose-gpu-utilization-python-example.py
  src/examples/python-examples/variorum-print-verbose-power-limit-python-example.py
  src/examples/python-examples/variorum-print-verbose-power-python-example.py
  src/examples/python-examples/variorum-print-verbose-thermals-python-example.py
  src/wrappers/python/README.rst
  src/wrappers/python/pyVariorum/__init__.py
  src/wrappers/python/pyVariorum/variorum.py
  src/wrappers/python/setup.py
Labels: status-work-in-progress, type-feature, area-feature-support

#337 Update docs for v0.6.0
  src/docs/sphinx/UnitTesting.rst
  src/docs/sphinx/VariorumAPI.rst
  src/docs/sphinx/VariorumTools.rst
  src/docs/sphinx/index.rst
Labels: status-ready-for-review, area-docs

#326 updates for 0.6.0 release
  ChangeLog.md
  README
  VERSION
  src/docs/dox/Doxyfile
  src/docs/dox/Doxyfile.in
  src/docs/sphinx/Releases.rst
  src/docs/sphinx/conf.py
  src/docs/sphinx/conf.py.in
Labels: status-ready-for-review, type-release

#341 add cztb2 runner to gitlab CI
  .gitlab-ci.yml
Labels: status-ready-for-review, type-internal-cleanup, area-ci

#345 Update Variorum Overview Figure
  src/docs/sphinx/images/VariorumSystemDesign.png
Labels: status-ready-for-review, type-internal-cleanup, area-docs
