Repository LLNL/variorum, pull requests merged in 2022-07, with the labels that each got.

#282 Move m_hostname and m_num_package to .c from .h
  src/variorum/ARM/power_features.c
  src/variorum/ARM/power_features.h
Labels: bug, Ready-For-Review

#288 docs: add contributing guide
  src/docs/sphinx/ContribGuide.rst
  src/docs/sphinx/index.rst
Labels: status-ready-for-review, area-docs

#281 Changing JSON API to use char** instead of json_t* as parameter.
  src/docs/sphinx/Examples.rst
  src/docs/sphinx/VariorumAPI.rst
  src/docs/sphinx/VariorumTools.rst
  src/examples/CMakeLists.txt
  src/examples/variorum-get-node-power-domain-info-json-example.c
  src/examples/variorum-get-node-power-json-example.c
  src/examples/variorum-integration-using-json-example.c
  src/variorum/AMD/epyc.c
  src/variorum/AMD/epyc.h
  src/variorum/ARM/ARM.c
  src/variorum/ARM/ARM.h
  src/variorum/IBM/Power9.c
  src/variorum/IBM/Power9.h
  src/variorum/Intel/Broadwell_4F.c
  src/variorum/Intel/Broadwell_4F.h
  src/variorum/Intel/Haswell_3F.c
  src/variorum/Intel/Haswell_3F.h
  src/variorum/Intel/IceLake_6A.c
  src/variorum/Intel/IceLake_6A.h
  src/variorum/Intel/IvyBridge_3E.c
  src/variorum/Intel/IvyBridge_3E.h
  src/variorum/Intel/KabyLake_9E.c
  src/variorum/Intel/KabyLake_9E.h
  src/variorum/Intel/SandyBridge_2A.c
  src/variorum/Intel/SandyBridge_2A.h
  src/variorum/Intel/SandyBridge_2D.c
  src/variorum/Intel/SandyBridge_2D.h
  src/variorum/Intel/Skylake_55.c
  src/variorum/Intel/Skylake_55.h
  src/variorum/config_architecture.h
  src/variorum/variorum.c
  src/variorum/variorum.h
Labels: status-ready-for-review, area-internal

#294 update filenames for Intel arch files
  README
  src/variorum/Intel/CMakeLists.txt
  src/variorum/Intel/Intel_06_2A.c
  src/variorum/Intel/Intel_06_2A.h
  src/variorum/Intel/Intel_06_2D.c
  src/variorum/Intel/Intel_06_2D.h
  src/variorum/Intel/Intel_06_3E.c
  src/variorum/Intel/Intel_06_3E.h
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_3F.h
  src/variorum/Intel/Intel_06_4F.c
  src/variorum/Intel/Intel_06_4F.h
  src/variorum/Intel/Intel_06_55.c
  src/variorum/Intel/Intel_06_55.h
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/Intel_06_6A.h
  src/variorum/Intel/Intel_06_9E.c
  src/variorum/Intel/Intel_06_9E.h
  src/variorum/Intel/config_intel.c
  src/variorum/config_architecture.h
  src/variorum/variorum.h
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#299 fix tables in rst files for rstfmt
  .github/workflows/github-actions.yml
  scripts/.ci-check-rst-format.sh
  scripts/check-rst-format.sh
  src/docs/sphinx/BuildingVariorum.rst
  src/docs/sphinx/Examples.rst
  src/docs/sphinx/IBM.rst
  src/docs/sphinx/VariorumAPI.rst
Labels: status-ready-for-review, type-internal-cleanup, area-docs

#298 Nvidia port cleanup
  host-configs/alehouse-rhel-gcc@4.8.5.cmake
  host-configs/boilerplate.cmake
  host-configs/butte-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake
  host-configs/butte-4.14.0-ppc64le-gcc@4.9.3.cmake
  host-configs/catalyst-toss_3_x86_64_ib-gcc@4.9.3.cmake
  host-configs/comus-ubuntu.20.04.2.LTS-x86_64-gcc@9.3.0.cmake
  host-configs/juno-armv8-gcc@5.2.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1-cuda@10.1.243.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1.cmake
  host-configs/octomore-ubuntu.20.04.2.LTS-x86_64-gcc@9.3.0.cmake
  host-configs/pluto5-rhel_x86_64-gcc@8.4.1.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@4.9.3.cmake
  host-configs/radon.cmake
  host-configs/ray-blueos_3_ppc64le-gcc@4.9.3.cmake
  host-configs/rhetoric-ubuntu.18.04.1.LTS-x86_64-gcc@7.3.0.cmake
  host-configs/thompson-centos_x86_64-gcc@4.8.5.cmake
  src/CMake/CMakeBasics.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/docs/sphinx/Nvidia.rst
  src/variorum/CMakeLists.txt
  src/variorum/Nvidia/config_nvidia.c
  src/variorum/Nvidia/config_nvidia.h
  src/variorum/Nvidia/power_features.c
  src/variorum/Nvidia/power_features.h
  src/variorum/config_architecture.c
  src/variorum/variorum_config.h.in
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#254 Adds -h and -v flags for all examples
  src/docs/sphinx/api/print_functions.rst
  src/examples/mpi-examples/variorum-cap-socket-power-limit-mpi-example.c
  src/examples/mpi-examples/variorum-print-power-limit-mpi-example.c
  src/examples/mpi-examples/variorum-print-power-mpi-example.c
  src/examples/mpi-examples/variorum-print-verbose-power-limit-mpi-example.c
  src/examples/mpi-examples/variorum-print-verbose-power-mpi-example.c
  src/examples/openmp-examples/variorum-cap-socket-power-limit-openmp-example.c
  src/examples/openmp-examples/variorum-print-power-limit-openmp-example.c
  src/examples/openmp-examples/variorum-print-power-openmp-example.c
  src/examples/openmp-examples/variorum-print-verbose-power-limit-openmp-example.c
  src/examples/openmp-examples/variorum-print-verbose-power-openmp-example.c
  src/examples/variorum-cap-best-effort-node-power-limit-example.c
  src/examples/variorum-cap-each-core-frequency-limit-example.c
  src/examples/variorum-cap-gpu-power-ratio-example.c
  src/examples/variorum-cap-socket-frequency-limit-example.c
  src/examples/variorum-cap-socket-power-limit-example.c
  src/examples/variorum-disable-turbo-example.c
  src/examples/variorum-enable-turbo-example.c
  src/examples/variorum-get-node-power-domain-info-json-example.c
  src/examples/variorum-get-node-power-json-example.c
  src/examples/variorum-get-topology-info-example.c
  src/examples/variorum-integration-using-json-example.c
  src/examples/variorum-monitoring-to-file-example.c
  src/examples/variorum-poll-power-to-file-example.c
  src/examples/variorum-poll-power-to-stdout-example.c
  src/examples/variorum-print-available-frequencies-example.c
  src/examples/variorum-print-counters-example.c
  src/examples/variorum-print-energy-example.c
  src/examples/variorum-print-features-example.c
  src/examples/variorum-print-frequency-example.c
  src/examples/variorum-print-gpu-utilization-example.c
  src/examples/variorum-print-hyperthreading-example.c
  src/examples/variorum-print-power-example.c
  src/examples/variorum-print-power-limit-example.c
  src/examples/variorum-print-thermals-example.c
  src/examples/variorum-print-topology-example.c
  src/examples/variorum-print-turbo-example.c
  src/examples/variorum-print-verbose-counters-example.c
  src/examples/variorum-print-verbose-frequency-example.c
  src/examples/variorum-print-verbose-gpu-utilization-example.c
  src/examples/variorum-print-verbose-power-example.c
  src/examples/variorum-print-verbose-power-limit-example.c
  src/examples/variorum-print-verbose-thermals-example.c
  src/variorum/variorum.c
  src/variorum/variorum.h
Labels: status-ready-for-review, area-internal

#301 Update PR template to include rstfmt and black related checklist items
  .github/pull_request_template.md
Labels: status-ready-for-review, type-internal-cleanup, area-docs

#295 AMD GPU Port with ROCM-SMI-lib
  README
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.1.cmake
  src/CMake/CMakeBasics.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMake/thirdparty/FindROCM.cmake
  src/CMakeLists.txt
  src/docs/sphinx/AMD.rst
  src/docs/sphinx/Argo.rst
  src/docs/sphinx/PowerStack.rst
  src/docs/sphinx/images/AMD_ESMS.png
  src/variorum/AMD_GPU/CMakeLists.txt
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/AMD_GPU/config_amd_gpu.h
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/AMD_GPU/instinctGPU.h
  src/variorum/AMD_GPU/power_features.c
  src/variorum/AMD_GPU/power_features.h
  src/variorum/CMakeLists.txt
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.h
  src/variorum/variorum_config.h.in
Labels: status-ready-for-review, type-feature, area-hardware-architecture

#308 update PR template
  .github/pull_request_template.md
Labels: status-ready-for-review

#270 Moves variorum_log to an environment variable.
  .github/workflows/github-actions.yml
  host-configs/boilerplate.cmake
  host-configs/butte-4.14.0-ppc64le-gcc@4.9.3.cmake
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.1.cmake
  host-configs/juno-armv8-gcc@5.2.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1.cmake
  host-configs/octomore-ubuntu.20.04.2.LTS-x86_64-gcc@9.3.0.cmake
  host-configs/pluto5-rhel_x86_64-gcc@8.4.1.cmake
  host-configs/radon.cmake
  src/CMake/CMakeBasics.cmake
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/variorum/AMD/epyc.c
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/ARM/ARM.c
  src/variorum/ARM/power_features.c
  src/variorum/IBM/Power9.c
  src/variorum/Intel/Intel_06_2A.c
  src/variorum/Intel/Intel_06_2D.c
  src/variorum/Intel/Intel_06_3E.c
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_4F.c
  src/variorum/Intel/Intel_06_55.c
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/Intel_06_9E.c
  src/variorum/Intel/config_intel.c
  src/variorum/Nvidia/Volta.c
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.c
  src/variorum/variorum_config.h.in
Labels: status-work-in-progress, type-internal-cleanup, area-internal

#307 AMD: bump ROCM version, fix build warnings
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.1.cmake
  src/docs/sphinx/AMD.rst
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/AMD_GPU/power_features.c
  src/variorum/config_architecture.c
Labels: status-ready-for-review, type-bug, area-hardware-architecture

#310 Fix arm port warnings
  src/variorum/ARM/ARM.c
  src/variorum/ARM/power_features.c
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#287 add autotools package config file
  src/config/CMakeLists.txt
  src/config/variorum.pc.in
Labels: status-ready-for-review, area-build-system
