Repository LLNL/variorum, pull requests merged in 2022-06, with the labels that each got.

#244 Refactors msr-related file paths.
  src/variorum/AMD/energy_feature.c
  src/variorum/msr/msr_core.c
  src/variorum/msr/msr_core.h
Labels: enhancement, Ready-For-Review

#243 initial intel icelake (6AH) support
  src/variorum/Intel/CMakeLists.txt
  src/variorum/Intel/IceLake_6A.c
  src/variorum/Intel/IceLake_6A.h
  src/variorum/Intel/config_intel.c
  src/variorum/config_architecture.h
Labels: enhancement, Ready-For-Review

#247 Changes comment in config_architecture.c to reflect current code
  src/variorum/config_architecture.c
Labels: documentation

#259 Check-code-format was not picking up c/h files in bash 5.1.4+.
  scripts/check-code-format.sh
Labels: Ready-For-Review

#228 Json query API other architectures.
  src/variorum/AMD/config_amd.c
  src/variorum/AMD/epyc.c
  src/variorum/AMD/epyc.h
  src/variorum/ARM/ARM.c
  src/variorum/ARM/ARM.h
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/power_features.c
  src/variorum/ARM/power_features.h
  src/variorum/Intel/Broadwell_4F.c
  src/variorum/Intel/Broadwell_4F.h
  src/variorum/Intel/Haswell_3F.c
  src/variorum/Intel/Haswell_3F.h
  src/variorum/Intel/IvyBridge_3E.c
  src/variorum/Intel/IvyBridge_3E.h
  src/variorum/Intel/KabyLake_9E.c
  src/variorum/Intel/KabyLake_9E.h
  src/variorum/Intel/SandyBridge_2A.c
  src/variorum/Intel/SandyBridge_2A.h
  src/variorum/Intel/SandyBridge_2D.c
  src/variorum/Intel/SandyBridge_2D.h
  src/variorum/Intel/Skylake_55.c
  src/variorum/Intel/Skylake_55.h
  src/variorum/Intel/config_intel.c
  src/variorum/Intel/power_features.c
  src/variorum/Intel/power_features.h
Labels: enhancement, Ready-For-Review

#269 add new header to expose topology get APIs
  src/examples/CMakeLists.txt
  src/examples/variorum-get-topology-info-example.c
  src/variorum/CMakeLists.txt
  src/variorum/config_architecture.c
  src/variorum/variorum_topology.c
  src/variorum/variorum_topology.h
Labels: enhancement, Ready-For-Review

#272 Add some documentation for the advanced API for topology functions.
  src/docs/sphinx/api/advanced_topology_functions.rst
  src/docs/sphinx/index.rst
  src/variorum/variorum_topology.h
Labels: documentation, Ready-For-Review
