Repository LLNL/variorum, pull requests merged in 2022-08, with the labels that each got.

#311 add corona to gitlab pipeline
  .gitlab-ci.yml
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.2.cmake
Labels: status-ready-for-review, type-internal-cleanup, area-ci

#319 Delete old TODO file
  TODO
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#312 replace #if defined with #ifdef
  src/variorum/config_architecture.c
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#313 make WITH_<ARCHITECTURE> CMake variables more descriptive
  host-configs/alehouse-rhel-gcc@4.8.5.cmake
  host-configs/boilerplate.cmake
  host-configs/butte-4.14.0-ppc64le-gcc@4.9.3-cuda@10.1.243.cmake
  host-configs/butte-4.14.0-ppc64le-gcc@4.9.3.cmake
  host-configs/catalyst-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/comus-ubuntu.20.04.2.LTS-x86_64-gcc@9.3.0.cmake
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.2.cmake
  host-configs/epyc-x86_64-gcc@8.4.0.cmake
  host-configs/juno-armv8-gcc@5.2.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1-cuda@10.1.243.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1.cmake
  host-configs/octomore-ubuntu.20.04.2.LTS-x86_64-gcc@9.3.0.cmake
  host-configs/pluto5-rhel_x86_64-gcc@8.4.1.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/radon.cmake
  host-configs/ray-blueos_3_ppc64le-gcc@4.9.3.cmake
  host-configs/rhetoric-ubuntu.18.04.1.LTS-x86_64-gcc@7.3.0.cmake
  host-configs/thompson-centos_x86_64-gcc@4.8.5.cmake
  src/CMake/CMakeBasics.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/tests/system-env/CMakeLists.txt
  src/variorum/CMakeLists.txt
  src/variorum/Nvidia/config_nvidia.c
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum_config.h.in
Labels: status-ready-for-review, type-internal-cleanup, area-build-system

#327 docs: add missing 0.5.0 release
  src/docs/sphinx/Releases.rst
Labels: status-ready-for-review, area-docs

#329 fix path to gcc on corona
  host-configs/corona-4.18.0toss-x86_64-gcc@10.3.1-rocm@5.2.cmake
Labels: status-ready-for-review, type-internal-cleanup, area-build-system
