Repository LLNL/variorum, pull requests merged in 2023-06, with the labels that each got.

#403 Sapphire Rapids initial port.
  README
  src/variorum/Intel/CMakeLists.txt
  src/variorum/Intel/Intel_06_8F.c
  src/variorum/Intel/Intel_06_8F.h
  src/variorum/Intel/config_intel.c
  src/variorum/config_architecture.h
  src/variorum/variorum.h
Labels: status-ready-for-review, area-hardware-support

#381 Support for ARM Neoverse N1 platform
  src/docs/sphinx/ARM.rst
  src/variorum/ARM/ARM.h
  src/variorum/ARM/ARM_Juno_r2.c
  src/variorum/ARM/ARM_Juno_r2.h
  src/variorum/ARM/ARM_Neoverse_N1.c
  src/variorum/ARM/ARM_Neoverse_N1.h
  src/variorum/ARM/CMakeLists.txt
  src/variorum/ARM/arm_util.c
  src/variorum/ARM/arm_util.h
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/power_features.h
  src/variorum/ARM/power_features_Juno_r2.c
  src/variorum/ARM/power_features_Juno_r2.h
  src/variorum/ARM/power_features_Neoverse_N1.c
  src/variorum/ARM/power_features_Neoverse_N1.h
  src/variorum/config_architecture.h
  src/variorum/variorum.h
Labels: status-ready-for-review, type-feature, area-hardware-support

#397 Powmon rehaul
  src/powmon/common.c
  src/powmon/power_wrapper_dynamic.c
  src/powmon/power_wrapper_static.c
  src/powmon/powmon.c
Labels: status-ready-for-review, type-feature, area-utilities

#407 Update filenames and low-level function names
  src/variorum/AMD/CMakeLists.txt
  src/variorum/AMD/config_amd.c
  src/variorum/AMD/epyc.c
  src/variorum/AMD/epyc.h
  src/variorum/AMD/power_features.c
  src/variorum/AMD/power_features.h
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/AMD_GPU/instinctGPU.h
  src/variorum/IBM/CMakeLists.txt
  src/variorum/IBM/Power9.c
  src/variorum/IBM/Power9.h
  src/variorum/IBM/config_ibm.c
  src/variorum/IBM/power_features.c
  src/variorum/IBM/power_features.h
  src/variorum/Intel/Intel_06_2A.c
  src/variorum/Intel/Intel_06_2A.h
  src/variorum/Intel/Intel_06_2D.c
  src/variorum/Intel/Intel_06_2D.h
  src/variorum/Intel/Intel_06_3E.c
  src/variorum/Intel/Intel_06_3E.h
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_3F.h
  src/variorum/Intel/Intel_06_4F.c
  src/variorum/Intel/Intel_06_4F.h
  src/variorum/Intel/Intel_06_55.c
  src/variorum/Intel/Intel_06_55.h
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/Intel_06_6A.h
  src/variorum/Intel/Intel_06_9E.c
  src/variorum/Intel/Intel_06_9E.h
  src/variorum/Intel/config_intel.c
  src/variorum/Intel_GPU/GPU.c
  src/variorum/Intel_GPU/GPU.h
  src/variorum/Intel_GPU/config_intel_gpu.c
Labels: status-ready-for-review

#418 Remove unnecessary call to obtain number of sockets from JSON example.
  src/examples/variorum-get-node-power-json-example.c
Labels: status-ready-for-review, type-internal-cleanup, area-examples

#377 Fix for multiplatform build (ARM+NVIDIA) error/warnings (issue #376)
  host-configs/nvhpc1-4.18.0-aarch64-gcc@8.5.0-cuda@525.60.13-both.cmake
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/power_features_Juno_r2.c
  src/variorum/Nvidia_GPU/Volta.c
  src/variorum/Nvidia_GPU/power_features.c
  src/variorum/Nvidia_GPU/power_features.h
Labels: status-ready-for-review

#419 remove readme from examples
  src/examples/README
Labels: status-ready-for-review, type-internal-cleanup, area-examples

#421 add links to recordings from ECP Tutorial 2023
  src/docs/sphinx/Publications.rst
Labels: status-ready-for-review, type-release, area-docs

#420 add link to youtube video
  src/docs/sphinx/Publications.rst
Labels: status-ready-for-review, type-release, area-docs

#417 Prefix power_features.* with architecture name
  src/variorum/AMD/CMakeLists.txt
  src/variorum/AMD/amd_power_features.c
  src/variorum/AMD/amd_power_features.h
  src/variorum/AMD/epyc.c
  src/variorum/AMD_GPU/CMakeLists.txt
  src/variorum/AMD_GPU/amd_gpu_power_features.c
  src/variorum/AMD_GPU/amd_gpu_power_features.h
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/ARM/ARM_Juno_r2.c
  src/variorum/ARM/ARM_Neoverse_N1.c
  src/variorum/ARM/CMakeLists.txt
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/juno_r2_power_features.c
  src/variorum/ARM/juno_r2_power_features.h
  src/variorum/ARM/neoverse_N1_power_features.c
  src/variorum/ARM/neoverse_N1_power_features.h
  src/variorum/IBM/CMakeLists.txt
  src/variorum/IBM/Power9.c
  src/variorum/IBM/ibm_power_features.c
  src/variorum/IBM/ibm_power_features.h
  src/variorum/Intel/CMakeLists.txt
  src/variorum/Intel/Intel_06_2A.c
  src/variorum/Intel/Intel_06_2D.c
  src/variorum/Intel/Intel_06_3E.c
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_4F.c
  src/variorum/Intel/Intel_06_55.c
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/Intel_06_8F.c
  src/variorum/Intel/Intel_06_9E.c
  src/variorum/Intel/counters_features.c
  src/variorum/Intel/intel_power_features.c
  src/variorum/Intel/intel_power_features.h
  src/variorum/Intel_GPU/CMakeLists.txt
  src/variorum/Intel_GPU/GPU.c
  src/variorum/Intel_GPU/config_intel_gpu.h
  src/variorum/Intel_GPU/intel_gpu_power_features.c
  src/variorum/Intel_GPU/intel_gpu_power_features.h
  src/variorum/Nvidia_GPU/CMakeLists.txt
  src/variorum/Nvidia_GPU/Volta.c
  src/variorum/Nvidia_GPU/config_nvidia.h
  src/variorum/Nvidia_GPU/nvidia_gpu_power_features.c
  src/variorum/Nvidia_GPU/nvidia_gpu_power_features.h
Labels: status-ready-for-review, type-internal-cleanup, area-internal

#422 Docs for v0.7
  src/docs/sphinx/BuildingVariorum.rst
  src/docs/sphinx/Contributors.rst
  src/docs/sphinx/Powmon.rst
Labels: status-ready-for-review, area-docs

#423 Parse and plot powmon power data
  src/powmon/scripts/powmon-plot.py
Labels: status-ready-for-review, area-utilities

#426 updates for 0.7.0 release
  ChangeLog.md
  README
  VERSION
  src/docs/dox/Doxyfile
  src/docs/dox/Doxyfile.in
Labels: status-ready-for-review, type-release
