Repository LLNL/variorum, pull requests merged in 2023-11, with the labels that each got.

#478 Remove tavern host config
  host-configs/tavern-gcc@4.8.5.cmake
Labels: status-ready-for-review, type-internal-cleanup, area-build-system

#468 Improve table output by adding libjustify as an optional dependency
  .github/workflows/github-actions.yml
  host-configs/lupine-ubuntu.22.04.1.LTS-gcc@11.3.0.cmake
  host-configs/nvhpc1-4.18.0-aarch64-gcc@8.5.0-cuda@525.60.13-both.cmake
  src/CMake/Setup3rdParty.cmake
  src/CMake/thirdparty/SetupLibjustify.cmake
  src/CMakeLists.txt
  src/variorum/AMD/amd_power_features.c
  src/variorum/AMD/epyc.c
  src/variorum/AMD_GPU/amd_gpu_power_features.c
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/ARM/juno_r2_power_features.c
  src/variorum/ARM/juno_r2_power_features.h
  src/variorum/ARM/neoverse_N1_power_features.c
  src/variorum/ARM/neoverse_N1_power_features.h
  src/variorum/CMakeLists.txt
  src/variorum/IBM/Power9.c
  src/variorum/IBM/ibm_power_features.c
  src/variorum/IBM/ibm_power_features.h
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/clocks_features.c
  src/variorum/Intel/counters_features.c
  src/variorum/Intel/intel_power_features.c
  src/variorum/Intel/misc_features.c
  src/variorum/Intel/misc_features.h
  src/variorum/Intel/thermal_features.c
  src/variorum/Intel_GPU/intel_gpu_power_features.c
  src/variorum/Nvidia_GPU/nvidia_gpu_power_features.c
  src/variorum/config_architecture.c
  src/variorum/variorum.c
Labels: status-ready-for-review, type-feature, area-internal

#483 CI: add output of model name from /proc/cpuinfo
  .github/workflows/github-actions.yml
Labels: status-ready-for-review, type-internal-cleanup, area-ci
