Repository LLNL/variorum, pull requests merged in 2024-03, with the labels that each got.

#490 Mega Merge: Add new JSON GPU get power API, make Node-level get power JSON API nested, enable multi-platform build
  .gitlab/corona-gpu-build-and-test.yml
  src/examples/CMakeLists.txt
  src/examples/python-examples/variorum-get-node-power-json-python-example.py
  src/examples/variorum-get-power-json-example.c
  src/examples/variorum-get-topology-info-example.c
  src/examples/variorum-integration-using-json-example.c
  src/powmon/common.c
  src/variorum/AMD/config_amd.c
  src/variorum/AMD/epyc.c
  src/variorum/AMD/epyc.h
  src/variorum/AMD_GPU/amd_gpu_power_features.c
  src/variorum/AMD_GPU/amd_gpu_power_features.h
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/AMD_GPU/instinctGPU.c
  src/variorum/AMD_GPU/instinctGPU.h
  src/variorum/ARM/ARM_Juno_r2.c
  src/variorum/ARM/ARM_Juno_r2.h
  src/variorum/ARM/ARM_Neoverse_N1.c
  src/variorum/ARM/ARM_Neoverse_N1.h
  src/variorum/ARM/config_arm.c
  src/variorum/ARM/juno_r2_power_features.c
  src/variorum/ARM/neoverse_N1_power_features.c
  src/variorum/IBM/Power9.c
  src/variorum/IBM/Power9.h
  src/variorum/IBM/config_ibm.c
  src/variorum/IBM/ibm_power_features.c
  src/variorum/Intel/Intel_06_2A.c
  src/variorum/Intel/Intel_06_2A.h
  src/variorum/Intel/Intel_06_2D.c
  src/variorum/Intel/Intel_06_2D.h
  src/variorum/Intel/Intel_06_3E.c
  src/variorum/Intel/Intel_06_3E.h
  src/variorum/Intel/Intel_06_3F.c
  src/variorum/Intel/Intel_06_3F.h
  src/variorum/Intel/Intel_06_4F.c
  src/variorum/Intel/Intel_06_4F.h
  src/variorum/Intel/Intel_06_55.c
  src/variorum/Intel/Intel_06_55.h
  src/variorum/Intel/Intel_06_6A.c
  src/variorum/Intel/Intel_06_6A.h
  src/variorum/Intel/Intel_06_8F.c
  src/variorum/Intel/Intel_06_8F.h
  src/variorum/Intel/Intel_06_9E.c
  src/variorum/Intel/Intel_06_9E.h
  src/variorum/Intel/config_intel.c
  src/variorum/Intel/intel_power_features.c
  src/variorum/Nvidia_GPU/Volta.c
  src/variorum/Nvidia_GPU/Volta.h
  src/variorum/Nvidia_GPU/config_nvidia.c
  src/variorum/Nvidia_GPU/nvidia_gpu_power_features.c
  src/variorum/Nvidia_GPU/nvidia_gpu_power_features.h
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.c
  src/variorum/variorum.h
  src/wrappers/python/pyVariorum/variorum.py
Labels: status-work-in-progress, area-docs, area-feature-support, area-examples

#516 Lassen use ci partition
  .gitlab/lassen-cpu-build-and-test.yml
  .gitlab/lassen-cpugpu-build-and-test.yml
  .gitlab/lassen-gpu-build-and-test.yml
Labels: type-release, area-ci, status-ready-to-merge

#519 Change uint<>_t assignments from -1 to 0
  src/variorum/AMD_GPU/amd_gpu_power_features.c
Labels: type-internal-cleanup, area-internal, status-ready-to-merge

#517 Cleanup pass
  src/powmon/highlander.h
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/ARM/arm_util.h
  src/variorum/Intel/Intel_06_2D.h
  src/variorum/Intel/Intel_06_55.h
  src/variorum/Intel/Intel_06_6A.h
  src/variorum/Intel/Intel_06_8F.h
  src/variorum/Intel/Intel_06_9E.h
  src/variorum/Nvidia_GPU/config_nvidia.c
  src/variorum/msr/msr_core.h
  src/variorum/variorum.h
  src/variorum/variorum_topology.h
Labels: status-ready-for-review, type-internal-cleanup, type-release

#525 Update utilization API to build on cpu-only systems, rename API to be generic
  src/docs/sphinx/VariorumAPI.rst
  src/docs/sphinx/api/json_support_functions.rst
  src/examples/CMakeLists.txt
  src/examples/variorum-get-node-utilization-json-example.c
  src/examples/variorum-get-utilization-json-example.c
  src/variorum/AMD_GPU/amd_gpu_power_features.c
  src/variorum/AMD_GPU/config_amd_gpu.c
  src/variorum/Nvidia_GPU/config_nvidia.c
  src/variorum/config_architecture.c
  src/variorum/config_architecture.h
  src/variorum/variorum.c
  src/variorum/variorum.h
Labels: area-feature-support, status-ready-to-merge

#528 Cleanup Juno r2 code to build with `-DENABLE_WARNINGS=ON`
  src/variorum/ARM/neoverse_N1_power_features.c
Labels: status-ready-to-merge

#510 Update powmon to report utilization in addition to power.
  src/powmon/README.md
  src/powmon/common.c
  src/powmon/power_wrapper_dynamic.c
  src/powmon/power_wrapper_static.c
  src/powmon/powmon.c
Labels: status-ready-for-review, area-feature-support, area-utilities

#523 rename powmon to var_monitor throughout
  scripts/license.py
  src/CMakeLists.txt
  src/docs/sphinx/BuildingVariorum.rst
  src/docs/sphinx/Powmon.rst
  src/docs/sphinx/VarMonitor.rst
  src/docs/sphinx/VariorumAPI.rst
  src/docs/sphinx/index.rst
  src/examples/variorum-monitoring-to-file-example.c
  src/examples/variorum-poll-power-to-file-example.c
  src/powmon/scripts/powmon-ibm-post-process.sh
  src/var_monitor/CMakeLists.txt
  src/var_monitor/README.md
  src/var_monitor/common.c
  src/var_monitor/highlander.c
  src/var_monitor/highlander.h
  src/var_monitor/power_wrapper_dynamic.c
  src/var_monitor/power_wrapper_static.c
  src/var_monitor/scripts/var_monitor-ibm-plot.R
  src/var_monitor/scripts/var_monitor-ibm-post-process.sh
  src/var_monitor/scripts/var_monitor-plot.py
  src/var_monitor/var_monitor.c
  src/variorum/ARM/juno_r2_power_features.c
  src/variorum/Intel/counters_features.c
  src/variorum/Intel/intel_power_features.c
Labels: status-ready-for-review, type-internal-cleanup, area-utilities

#328 bugfix: fix Intel DRAM overflow issue
  src/variorum/Intel/intel_power_features.c
  src/variorum/Intel/intel_power_features.h
Labels: status-ready-for-review, type-bug, area-feature-support

#531 lassen: add path to cuda/10.1.243 to host configs
  .gitlab/lassen-gpu-build-and-test.yml
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1-cuda@10.1.243-both.cmake
  host-configs/lassen-4.14.0-ppc64le-gcc@8.3.1-cuda@10.1.243.cmake
Labels: type-release, area-ci, status-ready-to-merge

#534 format headers
  src/variorum/Intel/intel_power_features.h
  src/variorum/Intel/thermal_features.h
  src/variorum/Intel/variorum_cpuid.h
Labels: type-release, area-internal, status-ready-to-merge

#536 fix function pointer for intel model/family 06-4f
  src/variorum/Intel/config_intel.c
Labels: status-ready-for-review, type-bug, area-feature-support

#521 updates for 0.8.0 release
  ChangeLog.md
  README
  VERSION
  src/docs/dox/Doxyfile
  src/docs/sphinx/Releases.rst
  src/docs/sphinx/api/json_support_functions.rst
  src/docs/sphinx/api/print_functions.rst
Labels: type-release, area-internal, status-approved
