Repository LLNL/variorum, pull requests merged in 2024-02, with the labels that each got.

#504 gitlab: update corona to run on a compute node
  .gitlab/corona-gpu-build-and-test.yml
Labels: area-ci, status-ready-to-merge

#507 add LLNL_FLUX_SCHEDULER_PARAMETERS to gitlab
  .gitlab/corona-gpu-build-and-test.yml
Labels: status-work-in-progress, area-ci

#508 Add host config for folsom
  host-configs/folsom-centos.3.10.0_x86_64-gcc@11.2.1.cmake
Labels: status-ready-for-review, area-ci

#512 Updates for ROCm 6.0.2 and new RSMI APIs.
  host-configs/corona-4.18.0toss4-x86_64-gcc@10.3.1-rocm@6.0.2.cmake
  host-configs/tioga-4.18.0toss.t4.x86_64-gcc@10.3.1-rocm@6.0.2-both.cmake
  host-configs/tioga-4.18.0toss.t4.x86_64-gcc@10.3.1-rocm@6.0.2.cmake
  src/CMake/thirdparty/FindROCM.cmake
  src/variorum/AMD_GPU/amd_gpu_power_features.c
Labels: status-ready-for-review, status-ready-to-merge

#514 gitlab: fix corona hostname file
  .gitlab/corona-gpu-build-and-test.yml
Labels: type-release, area-ci, status-ready-to-merge

#515 github CI: remove verify build job
  .github/workflows/github-actions.yml
Labels: type-release, area-ci, status-ready-to-merge
